variables:
  GIT_SUBMODULE_STRATEGY: recursive


#image: gcc
image: ubuntu:18.04

stages:
  - test


before_script:
  - apt update -qq
  # - apt -qq -y install lsb
  - apt -qq -y install libboost-all-dev
  - apt -qq -y install g++
  - apt -qq -y install git
  - apt -qq -y install cmake
  - apt -qq -y install libfftw3-dev
  
  # - lsb_release -a
  - uname -a
  - cmake --version
  - dpkg -s libboost-all-dev

test:
  stage: test
  script:
    - pwd
    - git status

    - mkdir -p build_simple
    - cd build_simple
    - cmake ..
    - make
    - ls -l
    - cd ..

    - mkdir -p build_full
    - cd build_full
    - cmake -DFFTSCARF_BUILD_TEST:BOOL=ON -DFFTSCARF_PLAN_PROTECTACCESS:BOOL=ON -DFFTSCARF_PRECISION_SINGLE:BOOL=ON -DFFTSCARF_PRECISION_DOUBLE:BOOL=ON -DFFTSCARF_PRECISION_LONGDOUBLE:BOOL=ON -DFFTSCARF_PRECISION_DEFAULT=32 -DFFTSCARF_FFT_OOURA:BOOL=ON -DFFTSCARF_FFT_FFTREAL:BOOL=ON -DFFTSCARF_FFT_PFFFT:BOOL=ON -DFFTSCARF_FFT_FFTW3:BOOL=ON -DFFTSCARF_FFT_FFTS:BOOL=ON ..
    - make
    - ls -l
    - cd test
    - ctest -V
    - cd ..
    - cd ..
